spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/fileflow}
spring.datasource.username=${DB_USER:fileflow}
spring.datasource.password=${DB_PASSWORD:fileflow}

spring.jpa.hibernate.ddl-auto=update

server.port=${PORT:8080}

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

fileflow.base-url=${APP_BASE_URL:http://localhost:8080}